# NumPy 简介

[**NumPy**](https://www.numpy.org/) 是 Python 中的一个科学计算库，是其他许多库（如 PyTorch、TensorFlow 等）的基础。

NumPy 的核心部分即为其提供的一个 n 维数组类 `numpy.ndarray` 以及围绕此类的一系列操作。这些操作不仅可以减少代码量，也可以同时提升代码运行的速度（因为 NumPy 在底层使用 C 实现了许多高效的算法，可以提高运算效率）。

`numpy.ndarray` 可以看作是 Python 中列表（list）的扩展。

NumPy 官方也提供了[速成教程](https://numpy.org/devdocs/user/quickstart.html)。

> **PS：**在机器学习中，一般这种 n 维数组被称为**张量（tensor）**。例如一维张量即为向量、二维张量为矩阵等。

一般导入 NumPy 库时使用以下语句:

In [1]:
import numpy as np

## 创建数组

创建 `numpy.ndarray` 时一般不会使用其构造函数；一般使用 NumPy 提供的一些其他的函数（所谓的“工厂方法”？）创建 `numpy.ndarray` 实例。

In [14]:
# 最常见：numpy.array(<array-like>)，将给定的序列转换为 numpy.ndarray

x = np.array([1, 2, 3, 4, 5])

print('x =\n{}'.format(x))

x =
[1 2 3 4 5]


In [20]:
# 给定步长/个数：numpy.arange 与 numpy.linspace

y = np.arange(0, 10, 2)   # np.arange(start, end, step)     语法与 Python 提供的 range 类似
z = np.linspace(0, 1, 11) # np.linspace(start, end, number) 数据类型为浮点数

print('y =\n{}'.format(y))
print()
print('z =\n{}'.format(z))

y =
[0 2 4 6 8]

z =
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [29]:
# 创建特殊的数组

a = np.eye(5)      # 5 阶单位矩阵（eye = I，而 I 代表 Identity Matrix），等价于 np.diag(np.ones(5))
b = np.diag(x)     # 对角线上为数组 x 的对角矩阵

c = np.empty((3, 5)) # 3x5 的空矩阵（可能包含垃圾值）
d = np.zeros((3, 5)) # 3x5 的全零矩阵
e = np.ones((3, 5))  # 3x5 的全一矩阵

print('a =\n{}'.format(a))
print()
print('b =\n{}'.format(b))
print()
print('c =\n{}'.format(c))
print()
print('d =\n{}'.format(d))
print()
print('e =\n{}'.format(e))

a =
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

b =
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

c =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

d =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

e =
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
